import Splashscreen from './Splashscreen';
import Homescreen from './Homescreen';
import Recipe from './Recipe/index';
import Profile from './Profile';
import Detail from './Detail';
import Lontong from './Lontong';
import Search from './Search';
import AddBlogForm from './konten';
export {Splashscreen, Homescreen, Recipe,Profile,Detail,Lontong,Search,AddBlogForm};
