import Splashscreen from './Splashscreen';
import Homescreen from './Homescreen';
import Recipe from './Recipe/index';
import Profile from './Profile';
import Detail from './Detail';
import Lontong from './Lontong';
import Search from './Search';
import AddBlogForm from './konten';
import EditBlogForm from './EditBlogForm';
import BlogDetail from './BlogDetail';
// import AddBlogResep from './AddblogResep';
export {Splashscreen, Homescreen, Recipe,Profile,Detail,Lontong,Search,AddBlogForm,EditBlogForm,BlogDetail};
